version: "3"

tasks:
  yaml:
    dir: "{{.DIR}}"
    cmds:
      - dhall-to-yaml --explain < {{.SRC}} > {{.DST}}
  dhall:
    cmds:
      - task: yaml
        vars:
          DIR: src/{{.NAME}}
          SRC: Deployment.dhall
          DST: ../../dst/{{.NAME}}.Deployment.yaml
      - task: yaml
        vars:
          DIR: src/{{.NAME}}
          SRC: Service.dhall
          DST: ../../dst/{{.NAME}}.Service.yaml
    sources:
      - src/{{.NAME}}/*.dhall
      - src/common/*.dhall
    generates:
      - dst/{{.NAME}}.Deployment.yaml
      - dst/{{.NAME}}.Service.yaml
  repo-updater:
    cmds:
      - task: dhall
        vars:
          NAME: repo-updater
