apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: "Handles repository metadata (not Git data) lookups and updates from external code hosts and other similar services."
  labels:
    deploy: sourcegraph
  name: repo-updater
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: repo-updater
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: repo-updater
        deploy: sourcegraph
    spec:
      containers:
        - image: "index.docker.io/sourcegraph/repo-updater:3.18.0@sha256:1a4992837e6abcc976fc22a7ccf15688c7b94b0361cd9896d851a03c0556b39e"
          name: repo-updater
          ports:
            - containerPort: 3182
              name: http
            - containerPort: 6060
              name: debug
          resources:
            limits:
              cpu: "100m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "500Mi"
        - args:
            - "--reporter.grpc.host-port=jaeger-collector:14250"
            - "--reporter.type=grpc"
          image: "index.docker.io/sourcegraph/jaeger-agent:3.18.0@sha256:fbe6a333c1984befd37d09d18e20a1629d44331614bca223d95d30285474eea3"
          name: jaeger-agent
          ports:
            - containerPort: 5778
              protocol: TCP
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          resources:
            limits:
              cpu: '1'
              memory: "500M"
            requests:
              cpu: "100m"
              memory: "100M"
